title: Big Dog Labs
email: mike@mikehathaway.com
description: >-
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: 'https://dev.bigdoglabs.com'
twitter_username: mikehathaway
github_username: mjh2902
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-include-cache
  - minimal-mistakes-jekyll
minimal_mistakes_skin: dark
